### ISSUE TITLE
As a hacker, I can submit my response

### ISSUE THREAD

**Issue by leonm1** [VandyHacks/vaken#263]

**Comment by cktang88** [comment]
Is this just POC that the form can post successfully?

**Comment by gfting** [comment]
Plan:
- Determine how to get the input text properly from the Application page; cannot use the updateMyProfile() function. Therefore, need to get the string from the Application page.

**Comment by gfting** [comment]
- [ ] Add a application.graphql.ts file
   - [ ] Add mutation and query for app info
- [ ] Schema.graphql.ts: 
   - [ ] Add/verify that types are up to date and correct for app field
- [ ] Resolvers [Add app resolver]
   - [ ] Add mutation resolver
- [ ] Update application component to post answer utilizing mutation

Maybes: [Application component frontend]
- [ ] Fetch questions themselves from backend, allowing us to specify questions and link the settings pane
- [ ] Do updateOnly one question at a time rather than global submit button; automatically updates on type
- [ ] Debouncing if updating every time that you type
   - Rather than multiple mutations, it waits until user stops typing, then sends full info over at once

**Comment by cktang88** [comment]
i believe we can close this now?
