### ISSUE TITLE
Use polka instead of Express

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#342]
Since we only use Express for like one tiny file, might as well use Polka https://github.com/lukeed/polka
compatible with express middleware, 90 LOC, no external deps

**Comment by konoikon** [comment]
I'm not sure if we want to proceed with this option. Since Polka hasn't released its first version yet, there is no type declaration file available through npm.

However, if we want to proceed, [this guy](https://gist.github.com/frzi/a1bc8e2064bf1022c48151afd91aeb2f) created a custom declaration file that is supported and edited by polka's author. How would you like to proceed with this?

**Comment by cktang88** [comment]
Ah I see. Thanks for investigating this. I think we should probably wait until the official types come out to implement this, shouldn't be too long.

For people following this, the link tracking types support here: https://github.com/lukeed/polka/issues/17

**Comment by bencooper222** [comment]
Project looks dead.
